name: projeqtor-dev

services:
  projeqtor:
    image: ghcr.io/kylhuk/projeqtor:${PROJEQTOR_VERSION:-latest}
    container_name: projeqtor-dev
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - projeqtor_data:/var/www/html/files
    environment:
      - TZ=${TIMEZONE:-UTC}
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:14
    container_name: projeqtor_postgres-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-projeqtor}
      - POSTGRES_USER=${DB_USER:-projeqtor}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-projeqtor_password}
      - TZ=${TIMEZONE:-UTC}
    command: postgres -c 'max_connections=200'
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-projeqtor}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  frontend:
    name: projeqtor_dev_frontend
  backend:
    name: projeqtor_dev_backend
    internal: true

volumes:
  projeqtor_data:
    name: projeqtor_dev_data
  postgres_data:
    name: projeqtor_dev_postgres_data
