name: Build and Push Docker Image

on:
  # Run when a new release branch is created
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*.*.*'
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 9.4.0)'
        required: true
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set version from input or branch/tag
        id: set-version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            # Get version from manual input
            VERSION="${{ github.event.inputs.version }}"
            git checkout "release-$VERSION" || git checkout main
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract version from tag (v9.4.0 -> 9.4.0)
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
          else
            # Extract version from branch name (release-9.4.0 -> 9.4.0)
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#release-}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building for version: $VERSION"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push projeqtor image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/projeqtor:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/projeqtor:latest
      
      - name: Create GitHub Release
        # Only run if triggered by a tag push
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ProjeQtOr ${{ env.VERSION }}
          body: |
            ProjeQtOr version ${{ env.VERSION }}
            
            Docker images available at:
            - `ghcr.io/${{ github.repository_owner }}/projeqtor:${{ env.VERSION }}`
            - `ghcr.io/${{ github.repository_owner }}/projeqtor:latest`
            
            To run with Docker Compose:
            ```
            docker-compose pull
            docker-compose up -d
            ```
          draft: false
          prerelease: false
